name: Wiki Build
on:
  push:
jobs:
  # 自动部署GitPage
  gitpage:
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false
    # 编译出静态页面
    - name: Install and Build
      run: cd docs && npm install && npm run build
  # 自动生成PDF
  pdf:
    needs: [ gitpage ]
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false
    # 生成PDF
    - name: Build PDF
      run: sudo docker run --rm -v ${{ github.workspace }}/pdf:/app/pdf iseason/docusaurus-to-pdf -u https://theflooddragon.github.io/Ratziel-Wiki/intro --output pdf/Ratziel-Wiki.pdf
    # 上传PDF
    - name: Capture Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: pdf/
        if-no-files-found: error
  # Release
  release:
    needs: [ pdf ]
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: Checkout Repository
      uses: actions/checkout@v2
    # 下载本体
    - name: Download Content
      uses: actions/download-artifact@v2
      with:
        name: Artifacts
    # 获取序号
    - name: Get Project version
      id: get_version
      run: |
        echo "Project version: $GITHUB_RUN_NUMBER"
        echo "::set-output name=project_version::$GITHUB_RUN_NUMBER"
      env:
        project_version: ${{ steps.get_version.outputs.project_version }}
    # 创建release
    - name: Create Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.project_version }}
        release_name: Auto Release ${{ steps.get_version.outputs.project_version }}
    # 向release上传pdf
    - name: Upload PDF file to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: Ratziel-Wiki.pdf
        asset_name: Ratziel-Wiki.pdf
        asset_content_type: application/zip
