name: Wiki Deploy

# 触发条件
on:
  # 手动触发
  workflow_dispatch:
  # 推送时触发
  push:
    # 只在下列路径变更时触发
    paths:
      - 'wiki/**'

# 设置权限
permissions:
  contents: write

# 默认设置
defaults:
  run:
    working-directory: ./wiki # 工作路径

# 任务
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
      # 设置 Node 版本
      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      # 打包静态文件
      - name: Install and Build
        run: npm install && npm run build
      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build